highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: https://nezha.github.io/
devurl: http://localhost:4000/
name: nezha
title: nezha | Another yet unique freak is showing a freakshow
description: "every day is a activity start"

my:
    displayName: Jack Joney
    realName: zhangyi
    realName_cn: 张熠
    jobTitle: "Master in Jiangnan University"
    contact:
        qq: 1061243497
        email: nezhaxiaozi@outlook.com
        github: http://www.github.com/nezha
        #qzone: http://744910240.qzone.qq.com
        #pinterest: https://www.pinterest.com/miblah/
        #tel: 15671542698
        address:
            country: China
            state: JiangSu
            city: WuXi
            distribute: Binhu
            postcode: 214122
            school: Jiangnan University
    skills:
        frontend: ["HTML | Markdown", "CSS | SASS", "JS | jQuery", "Bootstrap"]
        backend: ["PHP", "MySQL", "Redis", "Regex", "Laravel", "OSC"]
        tools: ["Sublime Text", "Git | Github", "Linux", "Jekyll | Liquid"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
